workspace:
  base: /go
  path: src/app

pipeline:
  pr_test:
    image: golang:1.9-alpine
    commands:
      - go test ./project1
      - go test ./project2

  build_project1_test:
    image: plugins/docker
    dockerfile: project1/Dockerfile
    registry: docker.c.ehe.io
    repo: docker.c.ehe.io/test1/${DRONE_REPO_NAME}_project1
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_COMMIT_SHA:0:6}"
      - latest
    when:
      event: push
      branch: master

  build_project1_prod:
    image: plugins/docker
    dockerfile: project1/Dockerfile
    registry: docker.c.ehe.io
    repo: docker.c.ehe.io/test1/${DRONE_REPO_NAME}_project1
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_TAG}"
      - latest
    when:
      event: tag
      branch: master

  build_project2_test:
    image: plugins/docker
    dockerfile: project2/Dockerfile
    registry: docker.c.ehe.io
    repo: docker.c.ehe.io/test1/${DRONE_REPO_NAME}_project2
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_COMMIT_SHA:0:6}"
      - latest
    when:
      event: push
      branch: master

  build_project2_prod:
    image: plugins/docker
    dockerfile: project2/Dockerfile
    registry: docker.c.ehe.io
    repo: docker.c.ehe.io/test1/${DRONE_REPO_NAME}_project2
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_TAG}"
      - latest
    when:
      event: tag
      branch: master
