workspace:
  base: /go
  path: src/github.com/app

clone:
  git:
    image: plugins/git

pipeline:
  clone_bytom:
    image: docker:git
    commands:
      - git clone https://github.com/Bytom/bytom.git /go/src/github.com/app/vendor/bytom

  unit_test:
    image: golang:1.9-alpine
    commands:
      - ls /go/src/github.com
      - go test ./project1
      - go test ./project2

  build_project1_test:
    image: plugins/docker
    dockerfile: project1/Dockerfile
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/go_test/project1
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_COMMIT_SHA:0:7}"
      - latest
    when:
      event: push
      branch: master

  build_project1_prod:
    image: plugins/docker
    dockerfile: project1/Dockerfile
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/go_test/project1
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_TAG}"
      - latest
    when:
      event: tag
      branch: master

  build_project2_test:
    image: plugins/docker
    dockerfile: project2/Dockerfile
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/go_test/project2
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_COMMIT_SHA:0:7}"
      - latest
    when:
      event: push
      branch: master

  build_project2_prod:
    image: plugins/docker
    dockerfile: project2/Dockerfile
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/go_test/project2
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_TAG}"
      - latest
    when:
      event: tag
      branch: master
